# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82b32696862e0bac2fcc40fdcbb119689c3ab7bd0d84375da8870dbe9aeeedafe2322db6fcf3b82f0d86db9e999a60d589a2b2727c9667f2dd6bf3ca7b27490b

test:
  secret_key_base: fdff4399e06ddffb5459b67ee89ed0fbbe7dd5d951de4566421cc72812603ccc62a56a37ff463fed2c40853acd96901725db505d176c5b5b560dd90101e4b3dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
